[tox]
envlist = py38,py39,py310,py311,py312,py313
skipsdist = True
skip_missing_interpreters = True

[testenv]
setenv =
    PYTHON="{envpython}"
commands =
    python build.py --modules
    ruff check .
    ruff format --check .
    {posargs:pytest core hscommon}
deps =
    .[dev]
